# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

graphical_horseshoe_map_Cpp <- function(X, t_alpha = 1.0, t_beta = 1.0, tol = 1e-4, max_iter = 200L, diff_type = "relative", verbose = 1L, alt_kappa = TRUE, fixed_tau = 0) {
    .Call(`_GHSGEM_graphical_horseshoe_map_Cpp`, X, t_alpha, t_beta, tol, max_iter, diff_type, verbose, alt_kappa, fixed_tau)
}

